#!/bin/bash
ORC_POD=$(kubectl get pods -l app=orchestrator-ms -o jsonpath='{.items[0].metadata.name}')
MEASURE_POD=$(kubectl get pods -l app=measure-ms -o jsonpath='{.items[0].metadata.name}')

kubectl exec "$ORC_POD" -- node -e "const fs = require('fs'); const code = \`const { Router } = require('express')\nconst expressJwt = require('express-jwt')\n\nconst { TOKEN_SECRET } = require('../../config/jwt.config')\nconst OrchestratorController = require('../controllers/orchestrator.controller')\n\nconst jwtMiddleware = expressJwt({ algorithms: ['HS256'], secret: TOKEN_SECRET })\nconst orchestratorController = new OrchestratorController()\nconst router = Router()\n\nrouter.get('/humidity', jwtMiddleware, orchestratorController.getMeasureService)\nrouter.get('/light', jwtMiddleware, orchestratorController.getMeasureService)\nrouter.get('/temperature', jwtMiddleware, orchestratorController.getMeasureService)\nrouter.get('/pictures', jwtMiddleware, orchestratorController.getMeasureService)\n\nrouter.post('/light', jwtMiddleware, orchestratorController.postMeasureService)\n\nrouter.get('/microcontrollers', jwtMiddleware, orchestratorController.getMicrocontrollers)\nrouter.post('/microcontrollers', jwtMiddleware, orchestratorController.postMicrocontrollers)\nrouter.put('/microcontrollers', jwtMiddleware, orchestratorController.putMicrocontrollers)\nrouter.delete('/microcontrollers', jwtMiddleware, orchestratorController.deleteMicrocontrollers)\n\nrouter.post('/login', orchestratorController.login)\nrouter.post('/register', orchestratorController.register)\nrouter.post('/refresh', orchestratorController.refresh)\n\nrouter.use((error, req, res, next) => {\n  if (error.name === expressJwt.UnauthorizedError.name) {\n    res.sendStatus(401)\n  }\n})\n\nmodule.exports = router\`; fs.writeFileSync('src/app/routes/orchestrator.routes.js', code);"

kubectl exec "$MEASURE_POD" -- node -e "const fs = require('fs'); const code = \`const { Router } = require('express')\n\nconst MeasureController = require('../controllers/measure.controller')\n\nconst router = Router()\nconst humidityController = new MeasureController('humidity')\nconst lightController = new MeasureController('light')\nconst temperatureController = new MeasureController('temperature')\nconst picturesController = new MeasureController('pictures')\n\nrouter.get('/humidity', humidityController.getMeasure)\nrouter.get('/humidities', humidityController.getMeasures)\n\nrouter.get('/light', lightController.getMeasure)\nrouter.get('/lights', lightController.getMeasures)\nrouter.post('/light', lightController.postLight)\n\nrouter.get('/temperature', temperatureController.getMeasure)\nrouter.get('/temperatures', temperatureController.getMeasures)\n\nrouter.get('/pictures', picturesController.getMeasure)\nrouter.get('/picturess', picturesController.getMeasures)\n\nmodule.exports = router\`; fs.writeFileSync('src/app/routes/measure.routes.js', code);"

kubectl exec "$ORC_POD" -- pkill node
kubectl exec "$MEASURE_POD" -- pkill node
