upstream orchestrator-ms {
  server orchestrator-ms;
}

server {
  listen 8080;

  location / {
    root /usr/share/nginx/html/browser/;
    index index.html;
    sendfile off;
    try_files $uri $uri/ /index.html;
  }

  location /humidity {
    proxy_pass http://orchestrator-ms/humidity;
  }

  location /light {
    proxy_pass http://orchestrator-ms/light;
  }

  location /temperature {
    proxy_pass http://orchestrator-ms/temperature;
  }

  location /pictures {
    proxy_pass http://orchestrator-ms/pictures;
  }

  location /microcontrollers {
    proxy_pass http://orchestrator-ms/microcontrollers;
  }

  location /login {
    proxy_pass http://orchestrator-ms/login;
  }

  location /register {
    proxy_pass http://orchestrator-ms/register;
  }

  location /refresh {
    proxy_pass http://orchestrator-ms/refresh;
  }

  location /socket.io/ {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;

    proxy_pass http://orchestrator-ms/socket.io/;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}

