const MICROCONTROLLERS_HOST = process.env.MICROCONTROLLERS_MS_HOSTNAME || 'localhost' // '192.168.99.100'
const MICROCONTROLLERS_PORT = process.env.MICROCONTROLLERS_MS_SERVICE_PORT || 6000
const PICTURE_INTERVAL_HOURS = parseFloat(process.env.PICTURE_INTERVAL_HOURS) || 10

module.exports = {
  B_TERMISTOR: 4275,
  MICROCONTROLLERS_MS: `${MICROCONTROLLERS_HOST}:${MICROCONTROLLERS_PORT}`,
  PING_TIMEOUT: 5000,
  TEN_HOURS_MS: PICTURE_INTERVAL_HOURS * 60 * 60 * 1000
}
