apiVersion: v1
kind: Service
metadata:
  name: fake-arduino-iot
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: fake-arduino-iot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-arduino-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-arduino-iot
  template:
    metadata:
      labels:
        app: fake-arduino-iot
    spec:
      containers:
      - name: fake-arduino-iot
        image: europe-west1-docker.pkg.dev/iot-microservices-gcp/iot-repo/fake-arduino-iot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      tolerations:
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
