apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_USERNAME
              name: secrets
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_PASSWORD
              name: secrets
        image: mongo:4.2.5
        imagePullPolicy: IfNotPresent
        name: mongo
        ports:
        - containerPort: 27017
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: run-volume
          mountPath: /var/run/mongodb
        - name: mongo-persistent-storage
          mountPath: /data/db
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 10
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: run-volume
        emptyDir: {}
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
