apiVersion: v1
kind: Service
metadata:
  name: mongo-config
  namespace: default
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-config
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-config
  namespace: default
spec:
  serviceName: mongo-config
  replicas: 1
  selector:
    matchLabels:
      app: mongo-config
  template:
    metadata:
      labels:
        app: mongo-config
    spec:
      containers:
      - name: mongo-config
        image: mongo:4.2.5
        command:
        - mongod
        - "--configsvr"
        - "--replSet"
        - "configrs"
        - "--port"
        - "27017"
        - "--bind_ip_all"
        ports:
        - containerPort: 27017
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: run-volume
          mountPath: /var/run/mongodb
        - name: config-data
          mountPath: /data/configdb
        resources:
          limits:
            cpu: "500m"
            memory: "768Mi"
          requests:
            cpu: "250m"
            memory: "512Mi"
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: run-volume
        emptyDir: {}
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      tolerations:
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  volumeClaimTemplates:
  - metadata:
      name: config-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
