apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
      - name: mongos
        image: mongo:4.2.5
        command:
        - mongos
        - "--configdb"
        - "configrs/mongo-config-0.mongo-config.default.svc.cluster.local:27017"
        - "--port"
        - "27017"
        - "--bind_ip_all"
        ports:
        - containerPort: 27017
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: run-volume
          mountPath: /var/run/mongodb
        resources:
          limits:
            cpu: "500m"
            memory: "768Mi"
          requests:
            cpu: "250m"
            memory: "512Mi"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MONGO_INITDB_ROOT_PASSWORD
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: run-volume
        emptyDir: {}
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      tolerations:
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
