apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-microservices
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sergioitremotejobs2025-sketch/GreenHouse_Arduino.git'
    targetRevision: HEAD
    path: manifests-k8s/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
