apiVersion: v1
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0
  MYSQL_ROOT_PASSWORD: ZjAwMWRlOWY5MGUxZWFlMTRmOGVmZjc3ODJjMmY4MTE=
  MYSQL_ROOT_USERNAME: cm9vdA==
  RABBITMQ_DEFAULT_USER: dXNlcg==
  RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQ=
  INTERNAL_API_KEY: MTIzNDU2Nzg5MGFiY2RlZjEyMzQ1Njc4OTBhYmNkZWY=
kind: Secret
metadata:
  name: secrets
  namespace: default
type: Opaque
